package me.athlaeos.valhallammo.items;

public enum ItemTreatment {
    SHARPENING_ROUGH,
    SHARPENING_FINE,
    TEMPERING,
    QUENCHING,
    LEATHER_BINDING,
    WAX_COATING,
    ARMOR_FITTING,
    REINFORCING_WOOD,
    REINFORCING_STONE,
    REINFORCING_GOLD,
    REINFORCING_IRON,
    REINFORCING_DIAMOND,
    REINFORCING_NETHERITE,
    POLISHING,
    ENGRAVING,
    HEATING,
    SUPERHEATING,
    STUDDING,
    GENERIC_IMPROVEMENT,
    UNENCHANTABLE
}
